name       : apr
version    : 1.5.2
release    : 3
source     :
    - http://mirror.netinch.com/pub/apache//apr/apr-1.5.2.tar.bz2 : 7d03ed29c22a7152be45b8e50431063736df9e1daa1ddf93f6a547ba7a28f67a
license    : Apache-2.0
summary    : The Apache Portable Runtime (APR) library provides an abstraction of operating-system level services
description: |
    The Apache Portable Runtime (APR) library provides an abstraction of operating-system level services such as file and network I/O, memory management, and so on.
builddeps  :
    - libtool
setup      : |
    %configure --disable-static \
        --enable-threads \
        --with-devrandom=/dev/urandom
build      : |
    %make
install    : |
    %make_install
