name       : apr
version    : 1.7.0
release    : 8
source     :
    - https://www-us.apache.org/dist/apr/apr-1.7.0.tar.bz2 : e2e148f0b2e99b8e5c6caa09f6d4fb4dd3e83f744aa72a952f94f5a14436f7ea
license    : Apache-2.0
component  : programming
summary    : The Apache Portable Runtime (APR) library provides an abstraction of operating-system level services
description: |
    The Apache Portable Runtime (APR) library provides an abstraction of operating-system level services such as file and network I/O, memory management, and so on.
builddeps  :
    - libtool
setup      : |
    %configure --disable-static \
        --enable-threads \
        --with-devrandom=/dev/urandom
build      : |
    %make
install    : |
    %make_install
check      : |
    make check -j1
