name       : apr
version    : 1.7.4
release    : 10
source     :
    - https://www.apache.org/dist/apr/apr-1.7.4.tar.bz2 : fc648de983f3a2a6c9e78dea1f180639bd2fad6c06d556d4367a701fe5c35577
homepage   : https://apr.apache.org/
license    : Apache-2.0
component  : programming
summary    : The Apache Portable Runtime (APR) library provides an abstraction of operating-system level services
description: |
    The Apache Portable Runtime (APR) library provides an abstraction of operating-system level services such as file and network I/O, memory management, and so on.
builddeps  :
    - libtool
setup      : |
    %configure --disable-static \
        --enable-threads \
        --with-devrandom=/dev/urandom
build      : |
    %make
install    : |
    %make_install
check      : |
    make check -j1
